### ISSUE TITLE
Question: What's the reason behind periodical instead of continuous synchronization?

### ISSUE THREAD

**Issue by paraenggu** [radiorabe/roaming-homes#2]
Could you please explain, what the reasons were to prefer the periodical (every minute) synchronization mechanism instead of using a file system monitor and use `-repeat watch` for continuous synchronization?

Thanks!

**Comment by smirta** [comment]
I've decided to use a synchronization every 60s after successful login because of possible performance limits when there are a lot of clients. Depending on what directories added to sync the client will be having an almost permanent connection to the server. This might also impact the CPU of the client if it has to monitor a deep directory structure. Can you elaborate how you would do it and then we can test it.

**Comment by paraenggu** [comment]
As discussed offline recently, you'll find a recent Unison build on [radiorabe/centos-rpm-unison251](https://github.com/radiorabe/centos-rpm-unison251). Despite the repository name, packages are available for [CentOS 7 as well as Fedora](https://build.opensuse.org/package/show/home:radiorabe:misc/unison251) ([installation instructions](https://software.opensuse.org//download.html?project=home%3Aradiorabe%3Amisc&package=unison251)). The packages also include the `unison-fsmonitor` which could be used for syncing on-demand (via inotify), rather than periodically scan the whole file system.

I don't know if this is a practical solution for our use case in the end, but would love to hear your feedback on this.

**Comment by smirta** [comment]
Thanks @paraenggu, I'll try that.
